Scarf/Web/Controllers/ScarfController.cs
#region Copyright and license
//
// SCARF - Security Audit, Access and Action Logging
// Copyright (c) 2014 ReBuildAll Solutions Ltd
//
// Author:
//    Lenard Gunda 
//
// Licensed under MIT license, see included LICENSE file for details
#endregion

using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Hosting;
using System.Web.Mvc;
using Scarf.DataSource;

namespace Scarf.Web.Controllers
{
    [ScarfAuthorize]
    public class ScarfController : Controller
    {
        public const int PAGE_SIZE = 50;

        public ActionResult Index( int? page )
        {
            ScarfDataSource dataSource = ScarfConfiguration.DataSourceFactory.CreateDataSourceInstance();

            var messages = new List<ScarfLogMessage>();
            var pageIndex = page.HasValue ? page.Value - 1 : 0;
            if (pageIndex < 0) pageIndex = 0;

            int totalMessages = dataSource.GetMessages(
                ScarfConfiguration.ConfigurationSection.ApplicationName,
                pageIndex, 
                PAGE_SIZE, 
                messages);

            ViewBag.TotalMessages = totalMessages;
            ViewBag.CurrentPage = pageIndex + 1;
            ViewBag.TotalPages = totalMessages/PAGE_SIZE + 1;
            
            return ScarfConfiguration.ViewResultFactory.Create(this, "Index", messages);
        }

        [HandleError(View="Index", ExceptionType=typeof(ArgumentException))]
        public ActionResult Details(Guid? id)
        {
            if (id.HasValue == false)
            {
                return RedirectToAction("Index");
            }

            ScarfDataSource dataSource = ScarfConfiguration.DataSourceFactory.CreateDataSourceInstance();

            ScarfLogMessage message = dataSource.GetMessageById(id.Value);
            if (message == null) return RedirectToAction("Index");

            return ScarfConfiguration.ViewResultFactory.Create(this, "Details", message);
        }

        public ActionResult Resource(string fileid)
        {
            var provider = new EmbeddedResourceVirtualPathProvider();

            VirtualFile file = provider.GetFile("/scarfresources/" + fileid);
            using (Stream stream = file.Open())
            {
                var contents = new byte[stream.Length];
                stream.Read(contents, 0, contents.Length);
                return new FileContentResult(contents, GetContentType(fileid));
            }
        }

        private string GetContentType(string id)
        {
            var extension = Path.GetExtension(id);
            if (extension != null && extension.ToLower() == ".css")
            {
                return "text/css";
            }
            if (extension != null && extension.ToLower() == ".js")
            {
                return "text/javascript";
            }

            return "application/octet-stream";
        }
    }
}

Scarf/Web/Views/Details.cshtml
@model Scarf.ScarfLogMessage
@using System.Web.Mvc
@using System.Web.Mvc.Html
<!doctype html>
<html>
    <head>
        <title>Details - Scarf Log Viewer</title>
        <link rel="stylesheet" type="text/css" href="/Scarf/Resource?fileid=scarf.css" />
    </head>
    <body>
       
        <header>
            <ul>
                <li>@Html.ActionLink("Home","Index", "Scarf")</li>
                <li><a href="https://github.com/ReBuildAll/scarf/wiki">Help</a></li>
            </ul>            
            <h1>Log message details</h1>
        </header>
        
        <table class="scarf narrow">
            <tbody>
                <tr>
                    <td>Computer: </td>
                    <td>@Model.Computer</td>
                </tr>
                <tr>
                    <td>Resource: </td>
                    <td>@Model.ResourceUri</td>
                </tr>
                <tr>
                    <td>Message class: </td>
                    <td>@Model.MessageClass.ToString()</td>
                </tr>
                <tr>
                    <td>Message type: </td>
                    <td>@Model.MessageType</td>
                </tr>
                <tr>
                    <td>Success/failure: </td>
                    <td>@(Model.Success.HasValue ? (Model.Success.Value ? "success" : "failure") : "n/a")</td>
                </tr>
                <tr>
                    <td>Message: </td>
                    <td>@Model.Message</td>
                </tr>
                <tr>
                    <td>Logged in user: </td>
                    <td>@Model.User</td>
                </tr>
                <tr>
                    <td>Logged at: </td>
                    <td>@Model.LoggedAt.ToShortDateString() @Model.LoggedAt.ToLongTimeString()</td>
                </tr>
            </tbody>
        </table>
        
        <h2>Details</h2>
        <pre class="scarf">@Model.Details</pre>
        
        @if (Model.AdditionalInfo != null)
        {
            <h2>Additional information</h2>

             foreach (var key in Model.AdditionalInfo.Keys)
             {
                 if (Model.AdditionalInfo[key] == null) { continue; }
                 
                 <h3>@key</h3>
                 <table class="scarf">
                     <tbody>
                         @foreach (var item in Model.AdditionalInfo[key])
                         {
                             <tr>
                                 <td>@item.Key</td>
                                 <td>@item.Value</td>
                             </tr>
                         }
                     </tbody>
                 </table>
             }
        }

        <footer>
            Scarf copyright &copy; 2014, ReBuildAll Solutions Ltd. - <a href="http://github.com/ReBuildAll/scarf">hosted on GitHub</a>
        </footer>
    </body>
</html>

Scarf/Web/Views/Index.cshtml
@model ICollection<Scarf.ScarfLogMessage>
@using System.Web.Mvc.Html
<!doctype html>
<html>
    <head>
        <title>Scarf Log Viewer</title>
        <link rel="stylesheet" type="text/css" href="/Scarf/Resource?fileid=scarf.css" />
    </head>
<body>
    <header>
        <ul>
            <li>@Html.ActionLink("Home", "Index", "Scarf")</li>
            <li><a href="https://github.com/ReBuildAll/scarf/wiki">Help</a></li>
        </ul>
        <h1>Scarf Log Viewer</h1>
    </header>
    <div>
        <em>There are @ViewBag.TotalMessages messages(s) in the log.</em>
    </div>
    <table class="scarf">
        <thead>
            <tr>
                <th>
                    Computer
                </th>
                <th>
                    Resource
                </th>
                <th>
                    Class
                </th>
                <th>
                    Type
                </th>
                <th>
                    Message
                </th>
                <th>
                    User
                </th>
                <th>
                    Timestamp
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var logMessage in Model)
            {
                <tr>
                    <td>@logMessage.Computer</td>
                    <td>@logMessage.ResourceUri</td>
                    <td>@logMessage.MessageClass.ToString()</td>
                    <td>@logMessage.MessageType</td>
                    <td>@logMessage.Message - @Html.ActionLink("Details", "Details", "Scarf", new { id = logMessage.EntryId.ToString("D") }, null)</td>
                    <td>@logMessage.User</td>
                    <td>@logMessage.LoggedAt.ToShortDateString() @logMessage.LoggedAt.ToLongTimeString()</td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th>
                    @if (ViewBag.CurrentPage > 1)
                    {
                        <a href="@Url.Action("Index", "Scarf", new { page = ViewBag.CurrentPage - 1 })">&lt;&lt;&lt; Previous page </a>
                    }
                </th>
                <th colspan="5">
                    Page @ViewBag.CurrentPage / @ViewBag.TotalPages
                </th>
                <th>
                    @if (ViewBag.CurrentPage < ViewBag.TotalPages)
                    {
                        <a href="@Url.Action("Index", "Scarf", new { page = ViewBag.CurrentPage + 1 })">Next page &gt;&gt;&gt;</a>
                    }
                </th>
            </tr>
        </tfoot>
    </table>

    <footer>
        Scarf copyright &copy; 2014, ReBuildAll Solutions Ltd. - <a href="http://github.com/ReBuildAll/scarf">hosted on GitHub</a>
    </footer>
</body>

</html>